web/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/
Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{
  // Homepage Route
  Route::name('home')->get('/', 'WelcomeController@welcome');
  Route::name('eventos')->get('/eventos', 'WelcomeController@eventos');
  Route::name('contactar')->get('/contactar', 'WelcomeController@contactar');
  Route::name('contactar.post')->post('/contactar', 'WelcomeController@postContactar');
  Route::name('about')->get('/sobre-o-colegio', 'WelcomeController@about');
  Route::name('informacoes')->get('/informacoes', 'WelcomeController@informacoes');
  Route::name('documentos.matricula')->get('/documentos-para-matricula', 'WelcomeController@documentosMatricula');
  Route::name('tabela.precos')->get('/tabela-de-precos', 'WelcomeController@tabelaDePrecos');
  Route::name('terms.conditions')->get('/termos-e-condicoes', 'WelcomeController@terms');
  Route::name('gallery')->get('/galeria', 'WelcomeController@gallery');

   Route::resource(
    'noticias',
    'NewsController', [
      'only'  => [
        'index',
        'show',
      ],
    ]);

  // Authentication Routes
  Auth::routes();

  // Public Routes
  Route::group(['middleware' => 'web'], function () {

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);
    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);
    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);
    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);
  });

  // Registered and Activated User Routes
  Route::group(['middleware' => ['auth', 'activated']], function () {
    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');
    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'dashboard.home',   'uses' => 'PagesManagementController@index']);
    // Show users profile - viewable by other users.
    Route::get('profile/{username}', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@show',
    ]);
  });

  // Registered, activated, and is current user routes.
  Route::group(['middleware'=> ['auth', 'activated', 'currentUser']], function () {
    // User Profile and Account Routes
    Route::resource(
        'profile',
        'ProfilesController', [
            'only'  => [
              'show',
              'edit',
              'update',
              'create',
            ],
        ]
    );

    Route::put('profile/{username}/updateUserAccount', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@updateUserAccount',
    ]);
    Route::put('profile/{username}/updateUserPassword', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@updateUserPassword',
    ]);
    Route::delete('profile/{username}/deleteUserAccount', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@deleteUserAccount',
    ]);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', [
        'uses'      => 'ProfilesController@userProfileAvatar',
    ]);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);

    Route::resource('estudantes/notas', 'StudentsMarksManagementController', [
      'names' => [
        'index'   => 'estudante.notas',
        'show'   => 'estudante.notas.show',
      ],
      'only' => [
        'index',
        'show',
      ],
    ]);

    Route::resource('estudantes/{ano_lectivo}/notas', 'StudentsMarksManagementController', [
      'names' => [
        'show'   => 'estudante.ano_lectivo.notas.show',
      ],
      'only' => [
        'show',
      ],
    ]);

    Route::resource('estudantes/disciplinas', 'StudentsSubjectsManagementController', [
      'names' => [
        'show'    => 'estudante.disciplina.show',
      ],
      'only' => [
        'show',
      ]
    ]);

    Route::resource('estudantes/matriculas', 'StudentsMatriculationsManagementController', [
      'names' => [
        'index'   => 'estudante.matriculas',
        'show'    => 'estudante.matricula.show',
      ],
      'only' => [
        'index',
        'show',
      ]
    ]);

    Route::resource('estudantes/pagamentos', 'StudentsPaymentsManagementController', [
      'names' => [
        'index'   => 'estudante.pagamentos',
        'edit'    => 'estudante.pagamento.edit',
        'update'  => 'estudante.pagamento.update',
      ],
      'except' => [
        'show',
        'create',
        'store',
        'destroy',
      ]
    ]);
  });

  // Registered, activated, and is admin routes.
  Route::group(['middleware'=> ['auth', 'activated', 'role:admin']], function () {
    Route::resource('/usuarios/deleted', 'SoftDeletesController', [
      'only' => [
          'index', 'show', 'update', 'destroy',
      ],
    ]);

    Route::resource('usuarios', 'UsersManagementController', [
      'names' => [
        'index'   => 'usuarios',
        'show' => 'usuario.show',
        'edit' => 'usuario.edit',
        'destroy' => 'usuario.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('professores', 'UsersManagementController', [
      'names' => [
        'index'   => 'professores',
        'show'   => 'professor.show',
        'edit' => 'professor.edit',
        'destroy' => 'professor.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('encarregados', 'UsersManagementController', [
      'names' => [
        'index'   => 'encarregados',
        'show' => 'encarregado.show',
        'edit' => 'encarregado.edit',
        'destroy' => 'encarregado.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('disciplinas', 'SubjectsManagementController', [
      'names' => [
        'index'   => 'disciplinas',
        'edit' => 'disciplina.edit',
        'destroy' => 'disciplina.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('contactos', 'ContactosManagementController', [
      'names' => [
        'index'   => 'contactos',
        'show' => 'contacto.show',
        'edit' => 'contacto.edit',
        'destroy' => 'contacto.destroy',
      ],
      'except' => [
        'deleted',
        'create',
        'store',
      ],
    ]);

    Route::name('estudante.matriculas.readmitir')->get('estudantes/matriculas/readmitir',
                                                       'StudentsManagementController@getReadmitir');
    Route::name('estudante.matriculas.readmitir')->post('estudantes/matriculas/readmitir',
                                                       'StudentsManagementController@postReadmitir');

    Route::resource('estudantes', 'StudentsManagementController', [
      'names' => [
        'index'   => 'estudantes',
        'destroy' => 'estudante.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('pagamentos', 'PaymentsManagementController', [
      'names' => [
        'index'   => 'pagamentos',
        'destroy' => 'pagamento.destroy',
      ],
    ]);


    Route::get('estudantes/adicionar/notas/create/{id}',[
      'as'=> 'estudante.notas.add.create',
      'uses' => 'AdminMarksManagementController@create'
    ]);

    Route::resource('estudantes/adicionar/notas',
      'AdminMarksManagementController',[
      'names' => [
        'index' => 'estudante.notas.add.index',
        'show'   =>  'estudante.notas.add.show',
        'store'  => 'estudante.notas.add.store',
      ],
      'except' => [
        'create',
        'edit',
      ],
    ]);

    Route::get('estudantes/adicionar/notas/ver/{student}', [
      'as' => 'student.get.marks',
      'uses' => 'AdminMarksManagementController@getMarks'
    ]);

    Route::get('estudantes/adicionar/notas/ver/current/{student}', [
      'as' => 'student.get.current.marks',
      'uses' => 'AdminMarksManagementController@getCurrentMarks'
    ]);

    Route::get('estudantes/adicionar/notas/ver/current/{student}/subject', [
      'as' => 'student.get.current.marks.by.subject',
      'uses' => 'AdminMarksManagementController@getCurrentMarksBySubject'
    ]);

    Route::get('estudantes/adicionar/disciplinas/ver/{student}', [
      'as' => 'student.get.subjects',
      'uses' => 'AdminMarksManagementController@getSubjects'
    ]);

    Route::resource('temas', 'ThemesManagementController', [
      'names' => [
        'index'   => 'temas',
        'show' => 'tema.show',
        'edit' => 'tema.edit',
        'destroy' => 'tema.destroy',
      ],
    ]);

    Route::group(['prefix' => 'admin'], function(){

web/app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
  protected $table = 'estudantes';

  protected $fillable = [
    'primeiro_nome',
    'sobrenome',
    'sexo',
    'nr_de_reg',
    'data_de_nascimento',
    'telefone',
    'endereco',
    'bilhete_de_identidade',
    'profissao',
    'estado_civil',
    'encarregado_id',
    'professor_id'
  ];

  public function user()
  {
    return $this->morphOne('App\Models\User', 'userable');
  }

  public function results()
  {
    return $this->hasMany('App\Models\Result');
  }

  public function encarregado()
  {
    return $this->belongsTo('App\Models\Guardian', 'encarregado_id');
  }

  public function matriculas()
  {
    return $this->hasMany('App\Models\Matricula', 'estudante_id');
  }

  public function disciplinas_cursadas()
  {
    return $this->hasMany('App\Models\StudentSubjectTaken', 'estudante_id');
  }

  public function getFullNomeAttribute()
  {
    return $this->primeiro_nome . " " . $this->sobrenome;
  }

  public function getNomeAttribute()
  {
    return $this->primeiro_nome . " " . $this->sobrenome;
  }
}

web/resources/views/management/students/deleted/index.blade.php
@extends('layouts.admin')

@section('template_title')
  Showing Users
@endsection

@section('template_linked_css')
  <link rel="stylesheet" type="text/css" href="{{asset('/css/dataTables.bootstrap.min.css')}}">
  <style type="text/css" media="screen">
    .users-table {
        border: 0;
    }
    .users-table tr td:first-child {
        padding-left: 15px;
    }
    .users-table tr td:last-child {
        padding-right: 15px;
    }
    .users-table.table-responsive,
    .users-table.table-responsive table {
        margin-bottom: .15em;
    }
  </style>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                      <div style="display: flex; justify-content: space-between; align-items: center;">
                        Showing Deleted Users
                        <a href="{{ route('usuarios') }}"
                           class="btn btn-primary btn-xs pull-right">
                            <i class="fa fa-fw fa-reply" aria-hidden="true"></i>
                            <span class="hidden-xs">Back to Users</span>
                        </a>
                      </div>
                    </div>
                    <div class="panel-body">
                      @if(count($users) === 0)
                        <tr>
                          <p class="text-center margin-half">
                            @lang('titles.noItemsFound')
                          </p>
                        </tr>
                      @else
                        <div class="table-responsive users-table">
                          <table class="table table-striped table-condensed data-table">
                            <thead>
                              <tr>
                                <th class="hidden-xxs">ID</th>
                                <th>Username</th>
                                <th class="hidden-xs hidden-sm">Email</th>
                                <th class="hidden-xs hidden-sm hidden-md">First Name</th>
                                <th class="hidden-xs hidden-sm hidden-md">Last Name</th>
                                <th class="hidden-xs hidden-sm">Role</th>
                                <th class="hidden-xs">Deleted</th>
                                <th class="hidden-xs">Deleted IP</th>
                                <th>Actions</th>
                                <th></th>
                                <th></th>
                              </tr>
                            </thead>
                            <tbody>
                              @foreach($users as $user)
                                  <tr>
                                      <td class="hidden-xxs">{{$user->id}}</td>
                                      <td>{{$user->name}}</td>
                                      <td class="hidden-xs hidden-sm"><a href="mailto:{{ $user->email }}" title="email {{ $user->email }}">{{ $user->email }}</a></td>
                                      <td class="hidden-xs hidden-sm hidden-md">
                                        {{$user->userable->primeiro_nome}}
                                      </td>
                                      <td class="hidden-xs hidden-sm hidden-md">
                                        {{$user->userable->sobrenome}}
                                      </td>
                                      <td class="hidden-xs hidden-sm">
                                        @foreach ($user->roles as $user_role)
                                          @if ($user_role->name == 'User')
                                            @php $labelClass = 'primary' @endphp
                                          @elseif ($user_role->name == 'Admin')
                                            @php $labelClass = 'warning' @endphp
                                          @elseif ($user_role->name == 'Unverified')
                                            @php $labelClass = 'danger' @endphp
                                          @else
                                            @php $labelClass = 'default' @endphp
                                          @endif

                                          <span class="label label-{{$labelClass}}">{{ $user_role->name }}</span>
                                        @endforeach
                                      </td>
                                      <td class="hidden-xs">{{$user->deleted_at}}</td>
                                      <td class="hidden-xs">{{$user->deleted_ip_address}}</td>
                                      <td>
                                          {!! Form::model($user, array('action' => array('SoftDeletesController@update', $user->id), 'method' => 'PUT', 'data-toggle' => 'tooltip')) !!}
                                            {!! Form::button('<i class="fa fa-refresh" aria-hidden="true"></i>', array('class' => 'btn btn-success btn-block btn-sm', 'type' => 'submit', 'data-toggle' => 'tooltip', 'title' => 'Restore User')) !!}
                                          {!! Form::close() !!}
                                      </td>
                                      <td>
                                        <a class="btn btn-sm btn-info btn-block" href="{{ route('deleted.show', $user->id) }}" data-toggle="tooltip" title="Show User">
                                          <i class="fa fa-eye fa-fw" aria-hidden="true"></i>
                                        </a>
                                      </td>
                                      <td>
                                          {!! Form::model($user, array('action' => array('SoftDeletesController@destroy', $user->id), 'method' => 'DELETE', 'class' => 'inline', 'data-toggle' => 'tooltip', 'title' => 'Destroy User Record')) !!}
                                            {!! Form::hidden('_method', 'DELETE') !!}
                                            {!! Form::button('<i class="fa fa-user-times" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm inline','type' => 'button', 'style' =>'width: 100%;' ,'data-toggle' => 'modal', 'data-target' => '#confirmDelete', 'data-title' => 'Delete User', 'data-message' => 'Are you sure you want to delete this user ?')) !!}
                                          {!! Form::close() !!}
                                      </td>
                                  </tr>
                              @endforeach
                            </tbody>
                          </table>
                        </div>
                      @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('modals.modal-delete')

@endsection

@section('footer_scripts')

    @if (count($users) > 10)
        @include('scripts.datatables')
    @endif
    @include('scripts.delete-modal-script')
    @include('scripts.save-modal-script')
    @include('scripts.tooltips')

@endsection

web/resources/views/management/students/deleted/show.blade.php
@extends('layouts.admin')

@section('template_title')
  Showing User {{ $user->name }}
@endsection

@php
  $levelAmount = 'Level:';

  if ($user->level() >= 2) {
      $levelAmount = 'Levels:';

  }
@endphp

@section('content')

  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="panel panel-danger">

          <div class="panel-heading">
            <a href="{{ route('deleted.index') }}" class="btn btn-primary btn-xs pull-right">
              <i class="fa fa-fw fa-mail-reply" aria-hidden="true"></i>
              <span class="hidden-xs">{{ trans('usersmanagement.usersBackDelBtn') }}</span>
            </a>
            {{ trans('usersmanagement.usersDeletedPanelTitle') }}
          </div>
          <div class="panel-body">

            <div class="well">
              <div class="row">
                <div class="col-sm-6">
                  <img src="@if ($user->profile->avatar_status == 1) {{ $user->profile->avatar }} @else {{ Gravatar::get($user->email) }} @endif" alt="{{ $user->name }}" id="" class="img-circle center-block margin-bottom-2 margin-top-1 user-image">
                </div>

                <div class="col-sm-6">
                  <h4 class="text-muted margin-top-sm-1 text-center text-left-tablet">
                    {{ $user->name }}
                  </h4>
                  <p class="text-center text-left-tablet">
                    <strong>
                      {{ $user->first_name }} {{ $user->last_name }}
                    </strong>
                    <br />
                    {{ HTML::mailto($user->email, $user->email) }}
                  </p>

                  @if ($user->profile)
                    <div class="text-center text-left-tablet margin-bottom-1">

                      {!! Form::model($user, array('action' => array('SoftDeletesController@update', $user->id), 'method' => 'PUT', 'class' => 'form-inline')) !!}
                          {!! Form::button('<i class="fa fa-refresh fa-fw" aria-hidden="true"></i> Restore User', array('class' => 'btn btn-success btn-block btn-sm', 'type' => 'submit', 'data-toggle' => 'tooltip', 'title' => 'Restore User')) !!}
                      {!! Form::close() !!}

                      {!! Form::model($user, array('action' => array('SoftDeletesController@destroy', $user->id), 'method' => 'DELETE', 'class' => 'form-inline', 'data-toggle' => 'tooltip', 'title' => 'Permanently Delete User')) !!}
                          {!! Form::hidden('_method', 'DELETE') !!}
                          {!! Form::button('<i class="fa fa-user-times fa-fw" aria-hidden="true"></i> Delete User', array('class' => 'btn btn-danger btn-sm','type' => 'button', 'style' =>'width: 100%;' ,'data-toggle' => 'modal', 'data-target' => '#confirmDelete', 'data-title' => 'Permanently Delete User', 'data-message' => 'Are you sure you want to permanently delete this user?')) !!}
                      {!! Form::close() !!}

                    </div>
                  @endif

                </div>
              </div>
            </div>

            <div class="clearfix"></div>
            <div class="border-bottom"></div>

            @if ($user->deleted_at)

              <div class="col-sm-5 col-xs-6 text-larger text-warning">
                <strong>
                  {{ trans('usersmanagement.labelDeletedAt') }}
                </strong>
              </div>

              <div class="col-sm-7 text-warning">
                {{ $user->deleted_at }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            @if ($user->deleted_ip_address)

              <div class="col-sm-5 col-xs-6 text-larger text-warning">
                <strong>
                  {{ trans('usersmanagement.labelIpDeleted') }}
                </strong>
              </div>

              <div class="col-sm-7 text-warning">
                {{ $user->deleted_ip_address }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif


            @if ($user->name)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelUserName') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->name }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            @if ($user->email)

            <div class="col-sm-5 col-xs-6 text-larger">
              <strong>
                {{ trans('usersmanagement.labelEmail') }}
              </strong>
            </div>

            <div class="col-sm-7">
              {{ HTML::mailto($user->email, $user->email) }}
            </div>

            <div class="clearfix"></div>
            <div class="border-bottom"></div>

            @endif

            @if ($user->first_name)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelFirstName') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->first_name }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            @if ($user->last_name)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelLastName') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->last_name }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            <div class="col-sm-5 col-xs-6 text-larger">
              <strong>
                {{ trans('usersmanagement.labelRole') }}
              </strong>
            </div>

            <div class="col-sm-7">
              @foreach ($user->roles as $user_role)

                @if ($user_role->name == 'User')
                  @php $labelClass = 'primary' @endphp

                @elseif ($user_role->name == 'Admin')
                  @php $labelClass = 'warning' @endphp

                @elseif ($user_role->name == 'Unverified')
                  @php $labelClass = 'danger' @endphp

                @else
                  @php $labelClass = 'default' @endphp

                @endif

                <span class="label label-{{$labelClass}}">{{ $user_role->name }}</span>

              @endforeach
            </div>

            <div class="clearfix"></div>
            <div class="border-bottom"></div>

            <div class="col-sm-5 col-xs-6 text-larger">
              <strong>
                {{ trans('usersmanagement.labelStatus') }}
              </strong>
            </div>

            <div class="col-sm-7">
              @if ($user->activated == 1)
                <span class="label label-success">
                  Activated
                </span>
              @else
                <span class="label label-danger">
                  Not-Activated
                </span>
              @endif
            </div>

            <div class="clearfix"></div>
            <div class="border-bottom"></div>

            <div class="col-sm-5 col-xs-6 text-larger">
              <strong>
                Access {{ trans('usersmanagement.labelAccessLevel')}} {{ $levelAmount }}:
              </strong>
            </div>

            <div class="col-sm-7">

              @if($user->level() >= 5)
                <span class="label label-primary margin-half margin-left-0">5</span>
              @endif

              @if($user->level() >= 4)
                 <span class="label label-info margin-half margin-left-0">4</span>
              @endif

              @if($user->level() >= 3)
                <span class="label label-success margin-half margin-left-0">3</span>
              @endif

              @if($user->level() >= 2)
                <span class="label label-warning margin-half margin-left-0">2</span>
              @endif

              @if($user->level() >= 1)
                <span class="label label-default margin-half margin-left-0">1</span>
              @endif

            </div>

            <div class="clearfix"></div>
            <div class="border-bottom"></div>

            <div class="col-sm-5 col-xs-6 text-larger">
              <strong>
                {{ trans('usersmanagement.labelPermissions') }}
              </strong>
            </div>

            <div class="col-sm-7">
              @if($user->canViewUsers())
                <span class="label label-primary margin-half margin-left-0"">
                  {{ trans('permsandroles.permissionView') }}
                </span>
              @endif

              @if($user->canCreateUsers())
                <span class="label label-info margin-half margin-left-0"">
                  {{ trans('permsandroles.permissionCreate') }}
                </span>
              @endif

              @if($user->canEditUsers())
                <span class="label label-warning margin-half margin-left-0"">
                  {{ trans('permsandroles.permissionEdit') }}
                </span>
              @endif

              @if($user->canDeleteUsers())
                <span class="label label-danger margin-half margin-left-0"">
                  {{ trans('permsandroles.permissionDelete') }}
                </span>
              @endif
            </div>

            <div class="clearfix"></div>
            <div class="border-bottom"></div>

            @if ($user->created_at)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelCreatedAt') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->created_at }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            @if ($user->updated_at)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelUpdatedAt') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->updated_at }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            @if ($user->signup_ip_address)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelIpEmail') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->signup_ip_address }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            @if ($user->signup_confirmation_ip_address)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelIpConfirm') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->signup_confirmation_ip_address }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            @if ($user->signup_sm_ip_address)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelIpSocial') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->signup_sm_ip_address }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            @if ($user->admin_ip_address)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelIpAdmin') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->admin_ip_address }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

            @if ($user->updated_ip_address)

              <div class="col-sm-5 col-xs-6 text-larger">
                <strong>
                  {{ trans('usersmanagement.labelIpUpdate') }}
                </strong>
              </div>

              <div class="col-sm-7">
                {{ $user->updated_ip_address }}
              </div>

              <div class="clearfix"></div>
              <div class="border-bottom"></div>

            @endif

          </div>

        </div>
      </div>
    </div>
  </div>

  @include('modals.modal-delete')

@endsection

@section('footer_scripts')

  @include('scripts.delete-modal-script')
  @include('scripts.tooltips')

@endsection