web/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/
Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{
  // Homepage Route
  Route::name('home')->get('/', 'WelcomeController@welcome');
  Route::name('eventos')->get('/eventos', 'WelcomeController@eventos');
  Route::name('contactar')->get('/contactar', 'WelcomeController@contactar');
  Route::name('contactar.post')->post('/contactar', 'WelcomeController@postContactar');
  Route::name('about')->get('/sobre-o-colegio', 'WelcomeController@about');
  Route::name('informacoes')->get('/informacoes', 'WelcomeController@informacoes');
  Route::name('documentos.matricula')->get('/documentos-para-matricula', 'WelcomeController@documentosMatricula');
  Route::name('tabela.precos')->get('/tabela-de-precos', 'WelcomeController@tabelaDePrecos');
  Route::name('terms.conditions')->get('/termos-e-condicoes', 'WelcomeController@terms');
  Route::name('gallery')->get('/galeria', 'WelcomeController@gallery');

   Route::resource(
    'noticias',
    'NewsController', [
      'only'  => [
        'index',
        'show',
      ],
    ]);

  // Authentication Routes
  Auth::routes();

  // Public Routes
  Route::group(['middleware' => 'web'], function () {

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);
    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);
    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);
    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);
  });

  // Registered and Activated User Routes
  Route::group(['middleware' => ['auth', 'activated']], function () {
    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');
    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'dashboard.home',   'uses' => 'PagesManagementController@index']);
    // Show users profile - viewable by other users.
    Route::get('profile/{username}', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@show',
    ]);
  });

  // Registered, activated, and is current user routes.
  Route::group(['middleware'=> ['auth', 'activated', 'currentUser']], function () {
    // User Profile and Account Routes
    Route::resource(
        'profile',
        'ProfilesController', [
            'only'  => [
              'show',
              'edit',
              'update',
              'create',
            ],
        ]
    );

    Route::put('profile/{username}/updateUserAccount', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@updateUserAccount',
    ]);
    Route::put('profile/{username}/updateUserPassword', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@updateUserPassword',
    ]);
    Route::delete('profile/{username}/deleteUserAccount', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@deleteUserAccount',
    ]);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', [
        'uses'      => 'ProfilesController@userProfileAvatar',
    ]);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);

    Route::resource('estudantes/notas', 'StudentsMarksManagementController', [
      'names' => [
        'index'   => 'estudante.notas',
        'show'   => 'estudante.notas.show',
      ],
      'only' => [
        'index',
        'show',
      ],
    ]);

    Route::resource('estudantes/{ano_lectivo}/notas', 'StudentsMarksManagementController', [
      'names' => [
        'show'   => 'estudante.ano_lectivo.notas.show',
      ],
      'only' => [
        'show',
      ],
    ]);

    Route::resource('estudantes/disciplinas', 'StudentsSubjectsManagementController', [
      'names' => [
        'show'    => 'estudante.disciplina.show',
      ],
      'only' => [
        'show',
      ]
    ]);

    Route::resource('estudantes/matriculas', 'StudentsMatriculationsManagementController', [
      'names' => [
        'index'   => 'estudante.matriculas',
        'show'    => 'estudante.matricula.show',
      ],
      'only' => [
        'index',
        'show',
      ]
    ]);

    Route::resource('estudantes/pagamentos', 'StudentsPaymentsManagementController', [
      'names' => [
        'index'   => 'estudante.pagamentos',
        'edit'    => 'estudante.pagamento.edit',
        'update'  => 'estudante.pagamento.update',
      ],
      'except' => [
        'show',
        'create',
        'store',
        'destroy',
      ]
    ]);
  });

  // Registered, activated, and is admin routes.
  Route::group(['middleware'=> ['auth', 'activated', 'role:admin']], function () {
    Route::resource('/usuarios/deleted', 'SoftDeletesController', [
      'only' => [
          'index', 'show', 'update', 'destroy',
      ],
    ]);

    Route::resource('usuarios', 'UsersManagementController', [
      'names' => [
        'index'   => 'usuarios',
        'show' => 'usuario.show',
        'edit' => 'usuario.edit',
        'destroy' => 'usuario.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('professores', 'UsersManagementController', [
      'names' => [
        'index'   => 'professores',
        'show'   => 'professor.show',
        'edit' => 'professor.edit',
        'destroy' => 'professor.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('encarregados', 'UsersManagementController', [
      'names' => [
        'index'   => 'encarregados',
        'show' => 'encarregado.show',
        'edit' => 'encarregado.edit',
        'destroy' => 'encarregado.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('disciplinas', 'SubjectsManagementController', [
      'names' => [
        'index'   => 'disciplinas',
        'edit' => 'disciplina.edit',
        'destroy' => 'disciplina.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('contactos', 'ContactosManagementController', [
      'names' => [
        'index'   => 'contactos',
        'show' => 'contacto.show',
        'edit' => 'contacto.edit',
        'destroy' => 'contacto.destroy',
      ],
      'except' => [
        'deleted',
        'create',
        'store',
      ],
    ]);

    Route::name('estudante.matriculas.readmitir')->get('estudantes/matriculas/readmitir',
                                                       'StudentsManagementController@getReadmitir');
    Route::name('estudante.matriculas.readmitir')->post('estudantes/matriculas/readmitir',
                                                       'StudentsManagementController@postReadmitir');

    Route::resource('estudantes', 'StudentsManagementController', [
      'names' => [
        'index'   => 'estudantes',
        'destroy' => 'estudante.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('pagamentos', 'PaymentsManagementController', [
      'names' => [
        'index'   => 'pagamentos',
        'destroy' => 'pagamento.destroy',
      ],
    ]);


    Route::get('estudantes/adicionar/notas/create/{id}',[
      'as'=> 'estudante.notas.add.create',
      'uses' => 'AdminMarksManagementController@create'
    ]);

    Route::resource('estudantes/adicionar/notas',
      'AdminMarksManagementController',[
      'names' => [
        'index' => 'estudante.notas.add.index',
        'show'   =>  'estudante.notas.add.show',
        'store'  => 'estudante.notas.add.store',
      ],
      'except' => [
        'create',
        'edit',
      ],
    ]);

    Route::get('estudantes/adicionar/notas/ver/{student}', [
      'as' => 'student.get.marks',
      'uses' => 'AdminMarksManagementController@getMarks'
    ]);

    Route::get('estudantes/adicionar/notas/ver/current/{student}', [
      'as' => 'student.get.current.marks',
      'uses' => 'AdminMarksManagementController@getCurrentMarks'
    ]);

    Route::get('estudantes/adicionar/notas/ver/current/{student}/subject', [
      'as' => 'student.get.current.marks.by.subject',
      'uses' => 'AdminMarksManagementController@getCurrentMarksBySubject'
    ]);

    Route::get('estudantes/adicionar/disciplinas/ver/{student}', [
      'as' => 'student.get.subjects',
      'uses' => 'AdminMarksManagementController@getSubjects'
    ]);

    Route::resource('temas', 'ThemesManagementController', [
      'names' => [
        'index'   => 'temas',
        'show' => 'tema.show',
        'edit' => 'tema.edit',
        'destroy' => 'tema.destroy',
      ],
    ]);

    Route::group(['prefix' => 'admin'], function(){

web/app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;

class Payment extends Model
{
  protected $table = 'pagamentos';
  protected $fillable = [
    'mes',
    'valor',
    'aprovado',
    'comprovativo',
    'trimestre_id',
    'estudante_id',
    'matricula_id',
  ];

  /**
  * The attributes that should be cast to native types.
  *
  * @var array
  */
  protected $casts = [
    'aprovado' => 'boolean',
  ];

  public function estudante()
  {
    return $this->belongsTo('App\Models\Student', 'estudante_id');
  }

  public function matricula()
  {
    return $this->belongsTo('App\Models\Matricula', 'matricula_id');
  }

  public function trimestre()
  {
    return $this->belongsTo('App\Models\Term', 'trimestre_id');
  }

  public function getMesAttribute($mes){
    $array = trans('months.months');
    $key = sprintf('%02d', $mes);
    if (!array_key_exists($key, $array)){
      return "Invalid";
    }
    
    return $array[$key];
  }
}

web/app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
  protected $table = 'estudantes';

  protected $fillable = [
    'primeiro_nome',
    'sobrenome',
    'sexo',
    'nr_de_reg',
    'data_de_nascimento',
    'telefone',
    'endereco',
    'bilhete_de_identidade',
    'profissao',
    'estado_civil',
    'encarregado_id',
    'professor_id'
  ];

  public function user()
  {
    return $this->morphOne('App\Models\User', 'userable');
  }

  public function results()
  {
    return $this->hasMany('App\Models\Result');
  }

  public function encarregado()
  {
    return $this->belongsTo('App\Models\Guardian', 'encarregado_id');
  }

  public function matriculas()
  {
    return $this->hasMany('App\Models\Matricula', 'estudante_id');
  }

  public function disciplinas_cursadas()
  {
    return $this->hasMany('App\Models\StudentSubjectTaken', 'estudante_id');
  }

  public function getFullNomeAttribute()
  {
    return $this->primeiro_nome . " " . $this->sobrenome;
  }

  public function getNomeAttribute()
  {
    return $this->primeiro_nome . " " . $this->sobrenome;
  }
}

web/resources/views/management/payments/edit.blade.php
@extends('layouts.admin')
@section('template_title')
  @lang('paymentsmanagement.editPayment') {{ $payment->estudante->nome }}
@endsection
@section('template_linked_css')
  <style type="text/css">
    .btn-save,
    .pw-change-container {
      display: none;
    }

    #comprovativo_emb{
      width: 500px;
      height: 600px;
    }
  </style>
@endsection
@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong>@lang('paymentsmanagement.editPayment'): </strong>  {{ $payment->estudante->nome }}
            <a href="{{ route('pagamentos.show', $payment->id) }}" class="btn btn-primary btn-xs pull-right" style="margin-left: 1em;">
              <i class="fa fa-fw fa-mail-reply" aria-hidden="true"></i>
              @lang('paymentsmanagement.backToPayment')
            </a>
            <a href="{{ route('pagamentos') }}" class="btn btn-info btn-xs pull-right">
              <i class="fa fa-fw fa-mail-reply" aria-hidden="true"></i>
              @lang('paymentsmanagement.backToPayments')
            </a>
          </div>
            {!! Form::model($payment, ['action' => ['PaymentsManagementController@update', $payment->id],
              'method' => 'PUT',
              'files' => true]) !!}
              {!! csrf_field() !!}
              <div class="panel-body">
                <div class="form-group has-feedback row {{ $errors->has('estudante_id') ? ' has-error ' : '' }}">
                  {!! Form::label('estudante_id', trans('forms.create_payment_label_student'),
                    array('class' => 'col-md-3 control-label')); !!}
                  <div class="col-md-9">
                    <div class="input-group">
                      <select class="form-control" name="estudante_id" id="estudante_id">
                        <option value="{{ old('estudante_id') }}">{{ trans('forms.create_payment_ph_student') }}</option>
                        @if ($students->count())
                          @foreach($students as $key_=>$student)
                            <option value="{{ $student->id }}" {{ $currentStudent ==  $student->id ? 'selected="selected"' : '' }}>
                              {{ $student->nome }}
                            </option>
                          @endforeach
                        @endif
                      </select>
                      <label class="input-group-addon" for="estudante_id">
                        <i class="fa fa-fw {{ trans('forms.create_payment_icon_student') }}"
                           aria-hidden="true"></i>
                      </label>
                    </div>
                    @if ($errors->has('estudante_id'))
                      <span class="help-block">
                          <strong>{{ $errors->first('estudante_id') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>
                <div class="form-group has-feedback row {{ $errors->has('aprovado') ? ' has-error ' : '' }}">
                  {!! Form::label('aprovado', trans('forms.create_payment_label_approved'), array('class' => 'col-md-3 control-label')); !!}
                  <div class="col-md-9">
                    <div class="input-group">
                      <select class="form-control" name="aprovado" id="aprovado">
                        <option value="{{ old('aprovado') }}">{{ trans('forms.create_payment_ph_approved') }}</option>
                        @if ($approveds->count())
                          @foreach($approveds as $key=>$approved)
                            <option value="{{ $key }}" {{ $currentState ==  $key ? 'selected="selected"' : '' }}>{{ $approved }}</option>
                          @endforeach
                        @endif
                      </select>
                      <label class="input-group-addon" for="approved">
                        <i class="fa fa-fw {{ trans('forms.create_payment_icon_approved') }}" aria-hidden="true"></i>
                      </label>
                    </div>
                    @if ($errors->has('aprovado'))
                      <span class="help-block">
                        <strong>{{ $errors->first('aprovado') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>
                <div class="form-group has-feedback row {{ $errors->has('mes') ? ' has-error ' : '' }}">
                  {!! Form::label('mes', trans('forms.create_payment_label_month'),
                                  array('class' => 'col-md-3 control-label')); !!}
                  <div class="col-md-9">
                    <div class="input-group">
                      <select name ='mes' class = "form-control">
                        <option value="{{ old('mes') }}">
                          {{ trans('forms.create_payment_ph_select_month') }}
                        </option>
                        @foreach(trans('months.months') as $key => $mes)
                          @php
                          // intval(ltrim($key, '0'));
                          $month = "";
                          if($payment->mes === trans('months.months')[$key] ) {
                            $month = $key;
                          }
                          if(old('mes') === $key OR  $month === $key)
                          {
                            $selected = 'selected="selected"';
                          }
                          else {
                            $selected = '';
                          }
                          @endphp
                          <option value="{{ $key}}" {{ $selected }}>
                            {{$mes}}
                          </option>
                        @endforeach
                      </select>
                      <label class="input-group-addon" for="mes">
                        <i class="fa fa-fw {{ trans('forms.create_payment_icon_month') }}"
                           aria-hidden="true"></i>
                      </label>
                    </div>
                    @if ($errors->has('mes'))
                      <span class="help-block">
                         <strong>{{ $errors->first('mes') }}</strong>
                      </span>
                    @endif
                  </div>
                </div>
                <div class="form-group has-feedback row {{ $errors->has('comprovativo') ? ' has-error ' : '' }}">
   								{!! Form::label('comprovativo',  trans('forms.create_payment_label_attachment'),
                    array('class' => 'col-md-3 control-label')); !!}
   								<div class="col-md-9">
   									<div class="image-preview">
                      <embed id="comprovativo_emb"
                              src="{{ asset($payment->comprovativo)}}"
                              type="application/pdf">
                          <a href="{{ asset($payment->comprovativo) }}">{{ $payment->comprovativo }}</a>
                      </embed>
   									</div>
   									<div class="input-group">
   										{!! Form::file('comprovativo', ['id' => 'comprovativo',
   																	  'class' => 'form-control required borrowerImageFile',
   																		'data-errormsg' => 'PhotoUploadErrorMsg',
   																		'placeholder' => trans('forms.create_payment-ph-comprovativo')
   																		]) !!}
   										<label class="input-group-addon" for="comprovativo">
   											<i class="fa fa-fw fa-file " aria-hidden="true"></i>
   										</label>
   									</div>
   									@if ($errors->has('comprovativo'))
   										<span class="help-block">
   											<strong>{{ $errors->first('comprovativo') }}</strong>
   										</span>
   									@endif
   								</div>
   							</div>
            </div>
            <div class="panel-footer">
              <div class="row">
                <div class="col-xs-6">
                  {!! Form::button('<i class="fa fa-fw fa-save" aria-hidden="true"></i> Save Changes',
                     array('class' => 'btn btn-success btn-block margin-bottom-1 btn-save',
                     'type' => 'button', 'data-toggle' => 'modal',
                     'data-target' => '#confirmSave',
                     'data-title' => trans('modals.edit_user__modal_text_confirm_title'),
                     'data-message' => trans('modals.edit_user__modal_text_confirm_message'))) !!}
                </div>
              </div>
            </div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>

  @include('modals.modal-save')
  @include('modals.modal-delete')
@endsection

@section('footer_scripts')
  @include('scripts.delete-modal-script')
  @include('scripts.save-modal-script')
  @include('scripts.check-changed')
  @include('scripts.file-preview')
@endsection

web/resources/views/management/payments/index.blade.php
@extends('layouts.admin')

@section('template_title')
  @lang('paymentsmanagement.showAllPayments')
@endsection

@section('template_linked_css')
  <link rel="stylesheet" type="text/css" href="{{asset('/css/dataTables.bootstrap.min.css')}}">
  <style type="text/css" media="screen">
    .payments-table {
        border: 0;
    }
    .payments-table tr td:first-child {
        padding-left: 15px;
    }
    .payments-table tr td:last-child {
        padding-right: 15px;
    }
    .payments-table.table-responsive,
    .payments-table.table-responsive table {
        margin-bottom: 0;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div style="display: flex; justify-content: space-between; align-items: center;">
              @lang('paymentsmanagement.showAllPayments')
              <div class="btn-group pull-right btn-group-xs">
                <button type="button"
                        class="btn btn-default dropdown-toggle"
                        data-toggle="dropdown"
                        aria-haspopup="true"
                        aria-expanded="false">
                  <i class="fa fa-ellipsis-v fa-fw" aria-hidden="true"></i>
                  <span class="sr-only">
                      @lang('titles.showingStudentsManagementMenu')
                  </span>
                </button>
                <ul class="dropdown-menu">
                  @role('admin')
                  <li>
                    <a href="{{ route('pagamentos.create') }}">
                      <i class="fa fa-fw fa-money" aria-hidden="true"></i>
                        @lang('titles.adminCreatePayment')
                    </a>
                  </li>
                 @endrole
                </ul>
              </div>
            </div>
          </div>
          <div class="panel-body">
            @if(count($payments) === 0)
              <tr>
                <p class="text-center margin-half">
                  @lang('titles.noItemsFound')
                </p>
              </tr>
            @else
              <div class="table-responsive payments-table">
                <table class="table table-striped table-condensed data-table">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>@lang('titles.name')</th>
                      <th>@lang('titles.month')</th>
                      <th>@lang('titles.approved')</th>
                      <th>@lang('titles.CreatedAt')</th>
                      <th>@lang('titles.UpdatedAt')</th>
                      <th>@lang('titles.actions')</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($payments as $payment)
                      <tr>
                        <td>{{$payment->id}}</td>
                        <td>{{$payment->estudante->nome}}</td>
                        <td>{{$payment->mes}}</td>
                        <td>
                          @include('partials.admin.label-aprovado',
                          ['aprovado' => $payment->aprovado])
                        </td>
                        <td class="hidden-sm hidden-xs hidden-md">{{$payment->created_at}}</td>
                        <td class="hidden-sm hidden-xs hidden-md">{{$payment->updated_at}}</td>
                        <td>
                          {!! Form::open(['url' => route('pagamento.destroy', $payment->id),
                            'class' => '',
                            'data-toggle' => 'tooltip',
                            'title' => trans('titles.delete')]) !!}
                            {!! Form::hidden('_method', 'DELETE') !!}
                            @php
                              $label = "<i class=\"fa fa-trash-o fa-fw\" aria-hidden=\"true\"></i>" .
                                     "<span class=\"hidden-xs hidden-sm\">" . trans('titles.delete') .
                                     "</span>";
                            @endphp
                            {!! Form::button($label,
                            array('class' => 'btn btn-danger btn-sm',
                            'type' => 'button', 'style' =>'width: 100%;' ,
                            'data-toggle' => 'modal', 'data-target' => '#confirmDelete',
                            'data-title' => 'Delete Subject',
                            'data-message' => 'Are you sure you want to delete this payment ?')) !!}
                          {!! Form::close() !!}
                        </td>
                        <td>
                          <a class="btn btn-sm btn-info btn-block"
                             href="{{ route('pagamentos.edit', $payment->id) }}"
                             data-toggle="tooltip"
                             title="@lang('titles.edit')">
                              <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>
                              <span class="hidden-xs hidden-sm">@lang('titles.edit')</span>
                          </a>
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            @endif
          </div>
        </div>
      </div>
    </div>
  </div>
  @include('modals.modal-delete')
@endsection

@section('footer_scripts')
  @if (count($payments) > 10)
    @include('scripts.datatables')
  @endif
  @include('scripts.delete-modal-script')
  @include('scripts.save-modal-script')
  @include('scripts.tooltips')
@endsection

web/resources/views/management/payments/show.blade.php
@extends('layouts.admin')

@section('template_title')
  @lang('studentsmanagement.editPayment') {{ $payment->estudante->nome }}
@endsection

@php

@endphp

@section('content')

  @include('modals.modal-delete')

@endsection

@section('footer_scripts')

  @include('scripts.delete-modal-script')

@endsection