web/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/
Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{
  // Homepage Route
  Route::name('home')->get('/', 'WelcomeController@welcome');
  Route::name('eventos')->get('/eventos', 'WelcomeController@eventos');
  Route::name('contactar')->get('/contactar', 'WelcomeController@contactar');
  Route::name('contactar.post')->post('/contactar', 'WelcomeController@postContactar');
  Route::name('about')->get('/sobre-o-colegio', 'WelcomeController@about');
  Route::name('informacoes')->get('/informacoes', 'WelcomeController@informacoes');
  Route::name('documentos.matricula')->get('/documentos-para-matricula', 'WelcomeController@documentosMatricula');
  Route::name('tabela.precos')->get('/tabela-de-precos', 'WelcomeController@tabelaDePrecos');
  Route::name('terms.conditions')->get('/termos-e-condicoes', 'WelcomeController@terms');
  Route::name('gallery')->get('/galeria', 'WelcomeController@gallery');

   Route::resource(
    'noticias',
    'NewsController', [
      'only'  => [
        'index',
        'show',
      ],
    ]);

  // Authentication Routes
  Auth::routes();

  // Public Routes
  Route::group(['middleware' => 'web'], function () {

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);
    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);
    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);
    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);
  });

  // Registered and Activated User Routes
  Route::group(['middleware' => ['auth', 'activated']], function () {
    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');
    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'dashboard.home',   'uses' => 'PagesManagementController@index']);
    // Show users profile - viewable by other users.
    Route::get('profile/{username}', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@show',
    ]);
  });

  // Registered, activated, and is current user routes.
  Route::group(['middleware'=> ['auth', 'activated', 'currentUser']], function () {
    // User Profile and Account Routes
    Route::resource(
        'profile',
        'ProfilesController', [
            'only'  => [
              'show',
              'edit',
              'update',
              'create',
            ],
        ]
    );

    Route::put('profile/{username}/updateUserAccount', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@updateUserAccount',
    ]);
    Route::put('profile/{username}/updateUserPassword', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@updateUserPassword',
    ]);
    Route::delete('profile/{username}/deleteUserAccount', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@deleteUserAccount',
    ]);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', [
        'uses'      => 'ProfilesController@userProfileAvatar',
    ]);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);

    Route::resource('estudantes/notas', 'StudentsMarksManagementController', [
      'names' => [
        'index'   => 'estudante.notas',
        'show'   => 'estudante.notas.show',
      ],
      'only' => [
        'index',
        'show',
      ],
    ]);

    Route::resource('estudantes/{ano_lectivo}/notas', 'StudentsMarksManagementController', [
      'names' => [
        'show'   => 'estudante.ano_lectivo.notas.show',
      ],
      'only' => [
        'show',
      ],
    ]);

    Route::resource('estudantes/disciplinas', 'StudentsSubjectsManagementController', [
      'names' => [
        'show'    => 'estudante.disciplina.show',
      ],
      'only' => [
        'show',
      ]
    ]);

    Route::resource('estudantes/matriculas', 'StudentsMatriculationsManagementController', [
      'names' => [
        'index'   => 'estudante.matriculas',
        'show'    => 'estudante.matricula.show',
      ],
      'only' => [
        'index',
        'show',
      ]
    ]);

    Route::resource('estudantes/pagamentos', 'StudentsPaymentsManagementController', [
      'names' => [
        'index'   => 'estudante.pagamentos',
        'edit'    => 'estudante.pagamento.edit',
        'update'  => 'estudante.pagamento.update',
      ],
      'except' => [
        'show',
        'create',
        'store',
        'destroy',
      ]
    ]);
  });

  // Registered, activated, and is admin routes.
  Route::group(['middleware'=> ['auth', 'activated', 'role:admin']], function () {
    Route::resource('/usuarios/deleted', 'SoftDeletesController', [
      'only' => [
          'index', 'show', 'update', 'destroy',
      ],
    ]);

    Route::resource('usuarios', 'UsersManagementController', [
      'names' => [
        'index'   => 'usuarios',
        'show' => 'usuario.show',
        'edit' => 'usuario.edit',
        'destroy' => 'usuario.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('professores', 'UsersManagementController', [
      'names' => [
        'index'   => 'professores',
        'show'   => 'professor.show',
        'edit' => 'professor.edit',
        'destroy' => 'professor.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('encarregados', 'UsersManagementController', [
      'names' => [
        'index'   => 'encarregados',
        'show' => 'encarregado.show',
        'edit' => 'encarregado.edit',
        'destroy' => 'encarregado.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('disciplinas', 'SubjectsManagementController', [
      'names' => [
        'index'   => 'disciplinas',
        'edit' => 'disciplina.edit',
        'destroy' => 'disciplina.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('contactos', 'ContactosManagementController', [
      'names' => [
        'index'   => 'contactos',
        'show' => 'contacto.show',
        'edit' => 'contacto.edit',
        'destroy' => 'contacto.destroy',
      ],
      'except' => [
        'deleted',
        'create',
        'store',
      ],
    ]);

    Route::name('estudante.matriculas.readmitir')->get('estudantes/matriculas/readmitir',
                                                       'StudentsManagementController@getReadmitir');
    Route::name('estudante.matriculas.readmitir')->post('estudantes/matriculas/readmitir',
                                                       'StudentsManagementController@postReadmitir');

    Route::resource('estudantes', 'StudentsManagementController', [
      'names' => [
        'index'   => 'estudantes',
        'destroy' => 'estudante.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('pagamentos', 'PaymentsManagementController', [
      'names' => [
        'index'   => 'pagamentos',
        'destroy' => 'pagamento.destroy',
      ],
    ]);


    Route::get('estudantes/adicionar/notas/create/{id}',[
      'as'=> 'estudante.notas.add.create',
      'uses' => 'AdminMarksManagementController@create'
    ]);

    Route::resource('estudantes/adicionar/notas',
      'AdminMarksManagementController',[
      'names' => [
        'index' => 'estudante.notas.add.index',
        'show'   =>  'estudante.notas.add.show',
        'store'  => 'estudante.notas.add.store',
      ],
      'except' => [
        'create',
        'edit',
      ],
    ]);

    Route::get('estudantes/adicionar/notas/ver/{student}', [
      'as' => 'student.get.marks',
      'uses' => 'AdminMarksManagementController@getMarks'
    ]);

    Route::get('estudantes/adicionar/notas/ver/current/{student}', [
      'as' => 'student.get.current.marks',
      'uses' => 'AdminMarksManagementController@getCurrentMarks'
    ]);

    Route::get('estudantes/adicionar/notas/ver/current/{student}/subject', [
      'as' => 'student.get.current.marks.by.subject',
      'uses' => 'AdminMarksManagementController@getCurrentMarksBySubject'
    ]);

    Route::get('estudantes/adicionar/disciplinas/ver/{student}', [
      'as' => 'student.get.subjects',
      'uses' => 'AdminMarksManagementController@getSubjects'
    ]);

    Route::resource('temas', 'ThemesManagementController', [
      'names' => [
        'index'   => 'temas',
        'show' => 'tema.show',
        'edit' => 'tema.edit',
        'destroy' => 'tema.destroy',
      ],
    ]);

    Route::group(['prefix' => 'admin'], function(){

web/app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
  protected $table = 'estudantes';

  protected $fillable = [
    'primeiro_nome',
    'sobrenome',
    'sexo',
    'nr_de_reg',
    'data_de_nascimento',
    'telefone',
    'endereco',
    'bilhete_de_identidade',
    'profissao',
    'estado_civil',
    'encarregado_id',
    'professor_id'
  ];

  public function user()
  {
    return $this->morphOne('App\Models\User', 'userable');
  }

  public function results()
  {
    return $this->hasMany('App\Models\Result');
  }

  public function encarregado()
  {
    return $this->belongsTo('App\Models\Guardian', 'encarregado_id');
  }

  public function matriculas()
  {
    return $this->hasMany('App\Models\Matricula', 'estudante_id');
  }

  public function disciplinas_cursadas()
  {
    return $this->hasMany('App\Models\StudentSubjectTaken', 'estudante_id');
  }

  public function getFullNomeAttribute()
  {
    return $this->primeiro_nome . " " . $this->sobrenome;
  }

  public function getNomeAttribute()
  {
    return $this->primeiro_nome . " " . $this->sobrenome;
  }
}

web/resources/views/management/students/create.blade.php
@extends('layouts.admin')

@section('template_title')
  @lang('titles.adminCreateStudent')
@endsection

@section('template_fastload_css')
@endsection

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        {!! Form::open(array('action' => 'StudentsManagementController@store',
          'method' => 'POST', 'role' => 'form')) !!}
        <div class="panel panel-default">
          <div class="panel-heading">
            @lang('titles.adminCreateStudent')
            <a href="{{ route('estudantes') }}" class="btn btn-info btn-xs pull-right">
              <i class="fa fa-fw fa-mail-reply" aria-hidden="true"></i>
              @lang('titles.back')
              <span class="hidden-xs">@lang('titles.to')</span>
              <span class="hidden-xs">@lang('titles.students')</span>
            </a>
          </div>
          <div class="panel-body">
            {!! csrf_field() !!}
            <div class="form-group has-feedback row {{ $errors->has('primeiro_nome') ? ' has-error ' : '' }}">
              {!! Form::label('primeiro_nome', trans('forms.create_user_label_firstname'),
                              array('class' => 'col-md-3 control-label')); !!}
              <div class="col-md-9">
                <div class="input-group">
                  {!! Form::text('primeiro_nome', NULL, array('id' => 'primeiro_nome', 'class' => 'form-control', 'placeholder' => trans('forms.create_user_ph_firstname'))) !!}
                  <label class="input-group-addon" for="name"><i class="fa fa-fw {{ trans('forms.create_user_icon_firstname') }}" aria-hidden="true"></i></label>
                </div>
                @if ($errors->has('primeiro_nome'))
                  <span class="help-block">
                      <strong>{{ $errors->first('primeiro_nome') }}</strong>
                  </span>
                @endif
              </div>
            </div>
            <div class="form-group has-feedback row {{ $errors->has('sobrenome') ? ' has-error ' : '' }}">
              {!! Form::label('sobrenome', trans('forms.create_user_label_lastname'), array('class' => 'col-md-3 control-label')); !!}
              <div class="col-md-9">
                <div class="input-group">
                  {!! Form::text('sobrenome', NULL, array('id' => 'sobrenome', 'class' => 'form-control', 'placeholder' => trans('forms.create_user_ph_lastname'))) !!}
                  <label class="input-group-addon" for="sobrenome"><i class="fa fa-fw {{ trans('forms.create_user_icon_lastname') }}" aria-hidden="true"></i></label>
                </div>
                @if ($errors->has('sobrenome'))
                  <span class="help-block">
                      <strong>{{ $errors->first('sobrenome') }}</strong>
                  </span>
                @endif
              </div>
            </div>
            <div class="form-group has-feedback row {{ $errors->has('email') ? ' has-error ' : '' }}">
              {!! Form::label('email', trans('forms.create_user_label_email'), array('class' => 'col-md-3 control-label')); !!}
              <div class="col-md-9">
                <div class="input-group">
                  {!! Form::text('email', NULL, array('id' => 'email', 'class' => 'form-control', 'placeholder' => trans('forms.create_user_ph_email'))) !!}
                  <label class="input-group-addon" for="email"><i class="fa fa-fw {{ trans('forms.create_user_icon_email') }}" aria-hidden="true"></i></label>
                </div>
                @if ($errors->has('email'))
                  <span class="help-block">
                      <strong>{{ $errors->first('email') }}</strong>
                  </span>
                @endif
              </div>
            </div>
            <div class="form-group has-feedback row {{ $errors->has('sexo') ? ' has-error ' : '' }}">
              {!! Form::label('sexo', trans('forms.create_user_label_sexo'), array('class' => 'col-md-3 control-label')); !!}
              <div class="col-md-9">
                <div class="input-group">
                  <select class="form-control" name="sexo" id="sexo">
                    <option value="{{ old('sexo') }}">{{ trans('forms.create_user_ph_sexo') }}</option>
                    @if (count($sexos))
                      @foreach($sexos as $sKey =>$sexo)
                        <option value="{{ $sKey}}" {{ old('sexo') == $sKey ? 'selected="selected"' : '' }}>{{ $sexo }}</option>
                      @endforeach
                    @endif
                  </select>
                  <label class="input-group-addon" for="sexo">
                    <i class="fa fa-fw {{ trans('forms.create_user_icon_sexo') }}" aria-hidden="true"></i>
                  </label>
                </div>
                @if ($errors->has('sexo'))
                  <span class="help-block">
                     <strong>{{ $errors->first('sexo') }}</strong>
                  </span>
                @endif
              </div>
            </div>
            <div class="form-group has-feedback row {{ $errors->has('data_de_nascimento') ? ' has-error ' : '' }}">
              {!! Form::label('data_de_nascimento', trans('forms.create_user_label_dob'), array('class' => 'col-md-3 control-label')); !!}
              <div class="col-md-9">
                <div class="input-group">
                  {!! Form::text('data_de_nascimento', NULL, array('id' => 'data_de_nascimento', 'class' => 'form-control', 'placeholder' => trans('forms.create_user_ph_dob'))) !!}
                  <label class="input-group-addon" for="data_de_nascimento"><i class="fa fa-fw {{ trans('forms.create_user_icon_dob') }}" aria-hidden="true"></i></label>
                </div>
                @if ($errors->has('data_de_nascimento'))
                  <span class="help-block">
                      <strong>{{ $errors->first('data_de_nascimento') }}</strong>
                  </span>
                @endif
              </div>
            </div>

            <div class="form-group has-feedback row {{ $errors->has('telefone') ? ' has-error ' : '' }}">
              {!! Form::label('telefone', trans('forms.create_user_label_mobile'), array('class' => 'col-md-3 control-label')); !!}
              <div class="col-md-9">
                <div class="input-group">
                  {!! Form::text('telefone', NULL, array('id' => 'telefone', 'class' => 'form-control', 'placeholder' => trans('forms.create_user_ph_mobile'))) !!}
                  <label class="input-group-addon" for="telefone">
                    <i class="fa fa-fw {{ trans('forms.create_user_icon_mobile') }}" aria-hidden="true"></i>
                  </label>
                </div>
                @if ($errors->has('telefone'))
                  <span class="help-block">
                      <strong>{{ $errors->first('telefone') }}</strong>
                  </span>
                @endif
              </div>
            </div>

            <div class="form-group has-feedback row {{ $errors->has('encarregado_id') ? ' has-error ' : '' }}">
              {!! Form::label('encarregado_id', trans('forms.create_user_label_guardian'),
              ['class' => 'col-md-3 control-label']) !!}
              <div class="col-md-9">
                <div class="input-group">
                  <select class="form-control" name="encarregado_id" id="encarregado_id">
                    <option value="">@lang('forms.create_user_ph_guardian')</option>
                    @if ($encarregados->count())
                      @foreach($encarregados as $encarregado)
                        <option value="{{ $encarregado->id }}" {{ old('encarregado_id') == $encarregado->id ? 'selected="selected"' : '' }}>
                          {{ $encarregado->nome }}
                        </option>
                      @endforeach
                    @endif
                  </select>
                  <label class="input-group-addon" for="encarregado_id">
                    <i class="fa fa-fw {{ trans('forms.create_user_icon_guardian') }}" aria-hidden="true"></i>
                  </label>
                </div>
                @if ($errors->has('encarregado_id'))
                  <span class="help-block">
                    <strong>{{ $errors->first('encarregado_id') }}</strong>
                  </span>
                @endif
              </div>
            </div>

            <div class="form-group has-feedback row {{ $errors->has('password') ? ' has-error ' : '' }}">
              {!! Form::label('password', trans('forms.create_user_label_password'), array('class' => 'col-md-3 control-label')); !!}
              <div class="col-md-9">
                <div class="input-group">
                  {!! Form::password('password', array('id' => 'password', 'class' => 'form-control ', 'placeholder' => trans('forms.create_user_ph_password'))) !!}
                  <label class="input-group-addon" for="password"><i class="fa fa-fw {{ trans('forms.create_user_icon_password') }}" aria-hidden="true"></i></label>
                </div>
                @if ($errors->has('password'))
                  <span class="help-block">
                      <strong>{{ $errors->first('password') }}</strong>
                  </span>
                @endif
              </div>
            </div>

            <div class="form-group has-feedback row {{ $errors->has('password_confirmation') ? ' has-error ' : '' }}">
              {!! Form::label('password_confirmation', trans('forms.create_user_label_pw_confirmation'), array('class' => 'col-md-3 control-label')); !!}
              <div class="col-md-9">
                <div class="input-group">
                  {!! Form::password('password_confirmation', array('id' => 'password_confirmation', 'class' => 'form-control', 'placeholder' => trans('forms.create_user_ph_pw_confirmation'))) !!}
                  <label class="input-group-addon" for="password_confirmation"><i class="fa fa-fw {{ trans('forms.create_user_icon_pw_confirmation') }}" aria-hidden="true"></i></label>
                </div>
                @if ($errors->has('password_confirmation'))
                  <span class="help-block">
                      <strong>{{ $errors->first('password_confirmation') }}</strong>
                  </span>
                @endif
              </div>
            </div>
          </div>
        </div>
        @include('partials.admin.matriculation')
        {!! Form::button('<i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;' . trans('forms.create_student_button_text'), array('class' => 'btn btn-success btn-flat margin-bottom-1 pull-right','type' => 'submit', )) !!}
        {!! Form::close() !!}
      </div>
    </div>
  </div>

@endsection

@section('footer_scripts')
  @include('scripts.date-picker')
@endsection

web/resources/views/management/students/index.blade.php
@extends('layouts.admin')

@section('template_title')
  @lang('titles.showingAllStudents')
@endsection

@section('template_linked_css')
  <link rel="stylesheet" type="text/css" href="{{asset('/css/dataTables.bootstrap.min.css')}}">
  <style type="text/css" media="screen">
    .students-table {
        border: 0;
    }
    .students-table tr td:first-child {
        padding-left: 15px;
    }
    .students-table tr td:last-child {
        padding-right: 15px;
    }
    .students-table.table-responsive,
    .students-table.table-responsive table {
        margin-bottom: 0;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <div style="display: flex; justify-content: space-between; align-items: center;">
              @lang('titles.showingAllStudents')
              <div class="btn-group pull-right btn-group-xs">
                <button type="button"
                        class="btn btn-default dropdown-toggle"
                        data-toggle="dropdown"
                        aria-haspopup="true"
                        aria-expanded="false">
                  <i class="fa fa-ellipsis-v fa-fw" aria-hidden="true"></i>
                  <span class="sr-only">
                      @lang('titles.showingStudentsManagementMenu')
                  </span>
                </button>
                <ul class="dropdown-menu">
                  @role('admin')
                  <li>
                    <a href="{{ route('estudantes.create') }}">
                      <i class="fa fa-fw fa-user-plus" aria-hidden="true"></i>
                        @lang('titles.adminCreateStudent')
                    </a>
                  </li>
                  <li>
                    <a href="{{ route($deleted_route) }}">
                      <i class="fa fa-fw fa-group" aria-hidden="true"></i>
                        @lang('titles.showDeletedStudent')
                    </a>
                  </li>
                  <li>
                    <a href="{{ route($notas_add) }}">
                      <i class="fa fa-fw fa-user-plus" aria-hidden="true"></i>
                        @lang('titles.addStudentsMarks')
                    </a>
                  </li>
                 @else
                   <li>
                     <a href="{{ route($payments_route) }}">
                       <i class="fa fa-fw fa-money" aria-hidden="true"></i>
                         @lang('titles.adminPaymentsList')
                     </a>
                   </li>
                 @endrole
                </ul>
              </div>
            </div>
          </div>

          <div class="panel-body">
            @if(count($students) === 0)
              <tr>
                <p class="text-center margin-half">
                  @lang('titles.noItemsFound')
                </p>
              </tr>
            @else
              <div class="table-responsive students-table">
                <table class="table table-striped table-condensed data-table">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>@lang('studentsmanagement.attrStdNumber')</th>
                      <th class="hidden-xs">@lang('studentsmanagement.attrName')</th>
                      <th class="hidden-xs">@lang('studentsmanagement.attrEmail')</th>
                      <th class="hidden-xs">@lang('studentsmanagement.attrGuardianName')</th>
                      <th class="hidden-xs">@lang('studentsmanagement.attrRole')</th>
                      <th class="hidden-xs">@lang('titles.CreatedAt')</th>
                      <th class="hidden-xs">@lang('titles.UpdatedAt')</th>
                      <th>@lang('titles.actions')</th>
                      <th></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($students as $student)
                      @if($student->user)
                      <tr>
                        <td>{{$student->id}}</td>
                        <td>{{$student->nr_de_reg}}</td>
                        <td>{{$student->nome}}</td>
                        <td class="hidden-xs">
                          <a href="mailto:{{ $student->user->email }}"
                            title="email {{ $student->user->email }}">
                            {{ $student->user->email }}
                          </a>
                        </td>
                        <td>{{$student->encarregado->nome}}</td>
                        <td>
                          @include('partials.admin.user_label_class',
                            ["user" => $student->user
                          ])
                        </td>
                        <td class="hidden-sm hidden-xs hidden-md">
                          {{$student->created_at->format('d-m-Y')}}
                        </td>
                        <td>{{$student->updated_at->format('d-m-Y')}}</td>
                        <td>
                          @role('admin')
                          {!! Form::open(['url' => route($destroy_route, $student->id),
                                          'class' => '',
                                          'data-toggle' => 'tooltip',
                                          'title' => trans('titles.delete')]) !!}
                            {!! Form::hidden('_method', 'DELETE') !!}
                            @php
                              $label = "<i class='fa fa-trash-o fa-fw' aria-hidden='true'></i>" .
                                       "<span class='hidden-xs hidden-sm'></span>";
                            @endphp
                            {!! Form::button($label,
                            array('class' => 'btn btn-danger btn-sm',
                                  'type' => 'button',
                                  'style' =>'width: 100%;' ,
                                  'data-toggle' => 'modal',
                                  'data-target' => '#confirmDelete',
                                  'data-title' => trans('studentsmanagement.deleteStudent'),
                                  'data-message' => trans('studentsmanagement.deleteStudentMsg'))) !!}
                           {!! Form::close() !!}
                           @endrole
                        </td>
                        <td>
                          <a class="btn btn-sm btn-success btn-block"
                             href="{{ route($show_route, $student->id) }}"
                             data-toggle="tooltip"
                             title="{{trans('titles.show')}}">
                            <i class="fa fa-eye fa-fw" aria-hidden="true"></i>
                            <span class="hidden-xs hidden-sm"></span>
                          </a>
                        </td>
                        <td>
                          <a class="btn btn-sm btn-info btn-block"
                          href="{{ route($edit_route, $student->id) }}"
                             data-toggle="tooltip"
                             title="{{trans('titles.edit')}}">
                            <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>
                            <span class="hidden-xs hidden-sm"></span>
                          </a>
                        </td>
                      </tr>
                      @endif
                    @endforeach
                  </tbody>
                  <tfoot>
                    <tr>
                      <th>ID</th>
                      <th class="hidden-xs">@lang('studentsmanagement.attrStdNumber')</th>
                      <th class="hidden-xs">@lang('studentsmanagement.attrName')</th>
                      <th class="hidden-xs">@lang('studentsmanagement.attrEmail')</th>
                      <th class="hidden-xs">@lang('studentsmanagement.attrGuardianName')</th>
                      <th class="hidden-xs">@lang('studentsmanagement.attrRole')</th>
                      <th class="hidden-xs">@lang('titles.CreatedAt')</th>
                      <th class="hidden-xs">@lang('titles.UpdatedAt')</th>
                      <th>@lang('titles.actions')</th>
                      <th></th>
                      <th></th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            @endif
          </div>
        </div>
      </div>
    </div>
  </div>

  @include('modals.modal-delete')

@endsection

@section('footer_scripts')
  @if (count($students) > 10)
    @include('scripts.datatables')
  @endif
  @include('scripts.delete-modal-script')
  @include('scripts.save-modal-script')
  {{-- @include('scripts.tooltips') --}}
@endsection