web/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/
Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{
  // Homepage Route
  Route::name('home')->get('/', 'WelcomeController@welcome');
  Route::name('eventos')->get('/eventos', 'WelcomeController@eventos');
  Route::name('contactar')->get('/contactar', 'WelcomeController@contactar');
  Route::name('contactar.post')->post('/contactar', 'WelcomeController@postContactar');
  Route::name('about')->get('/sobre-o-colegio', 'WelcomeController@about');
  Route::name('informacoes')->get('/informacoes', 'WelcomeController@informacoes');
  Route::name('documentos.matricula')->get('/documentos-para-matricula', 'WelcomeController@documentosMatricula');
  Route::name('tabela.precos')->get('/tabela-de-precos', 'WelcomeController@tabelaDePrecos');
  Route::name('terms.conditions')->get('/termos-e-condicoes', 'WelcomeController@terms');
  Route::name('gallery')->get('/galeria', 'WelcomeController@gallery');

   Route::resource(
    'noticias',
    'NewsController', [
      'only'  => [
        'index',
        'show',
      ],
    ]);

  // Authentication Routes
  Auth::routes();

  // Public Routes
  Route::group(['middleware' => 'web'], function () {

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);
    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);
    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);
    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);
  });

  // Registered and Activated User Routes
  Route::group(['middleware' => ['auth', 'activated']], function () {
    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');
    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'dashboard.home',   'uses' => 'PagesManagementController@index']);
    // Show users profile - viewable by other users.
    Route::get('profile/{username}', [
        'as'        => '{username}',
        'uses'      => 'ProfilesController@show',
    ]);
  });

  // Registered, activated, and is current user routes.
  Route::group(['middleware'=> ['auth', 'activated', 'currentUser']], function () {
    // User Profile and Account Routes
    Route::resource(
        'profile',
        'ProfilesController', [
            'only'  => [
              'show',
              'edit',
              'update',
              'create',
            ],
        ]
    );

    Route::put('profile/{username}/updateUserAccount', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@updateUserAccount',
    ]);
    Route::put('profile/{username}/updateUserPassword', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@updateUserPassword',
    ]);
    Route::delete('profile/{username}/deleteUserAccount', [
      'as'        => '{username}',
      'uses'      => 'ProfilesController@deleteUserAccount',
    ]);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', [
        'uses'      => 'ProfilesController@userProfileAvatar',
    ]);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);

    Route::resource('estudantes/notas', 'StudentsMarksManagementController', [
      'names' => [
        'index'   => 'estudante.notas',
        'show'   => 'estudante.notas.show',
      ],
      'only' => [
        'index',
        'show',
      ],
    ]);

    Route::resource('estudantes/{ano_lectivo}/notas', 'StudentsMarksManagementController', [
      'names' => [
        'show'   => 'estudante.ano_lectivo.notas.show',
      ],
      'only' => [
        'show',
      ],
    ]);

    Route::resource('estudantes/disciplinas', 'StudentsSubjectsManagementController', [
      'names' => [
        'show'    => 'estudante.disciplina.show',
      ],
      'only' => [
        'show',
      ]
    ]);

    Route::resource('estudantes/matriculas', 'StudentsMatriculationsManagementController', [
      'names' => [
        'index'   => 'estudante.matriculas',
        'show'    => 'estudante.matricula.show',
      ],
      'only' => [
        'index',
        'show',
      ]
    ]);

    Route::resource('estudantes/pagamentos', 'StudentsPaymentsManagementController', [
      'names' => [
        'index'   => 'estudante.pagamentos',
        'edit'    => 'estudante.pagamento.edit',
        'update'  => 'estudante.pagamento.update',
      ],
      'except' => [
        'show',
        'create',
        'store',
        'destroy',
      ]
    ]);
  });

  // Registered, activated, and is admin routes.
  Route::group(['middleware'=> ['auth', 'activated', 'role:admin']], function () {
    Route::resource('/usuarios/deleted', 'SoftDeletesController', [
      'only' => [
          'index', 'show', 'update', 'destroy',
      ],
    ]);

    Route::resource('usuarios', 'UsersManagementController', [
      'names' => [
        'index'   => 'usuarios',
        'show' => 'usuario.show',
        'edit' => 'usuario.edit',
        'destroy' => 'usuario.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('professores', 'UsersManagementController', [
      'names' => [
        'index'   => 'professores',
        'show'   => 'professor.show',
        'edit' => 'professor.edit',
        'destroy' => 'professor.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('encarregados', 'UsersManagementController', [
      'names' => [
        'index'   => 'encarregados',
        'show' => 'encarregado.show',
        'edit' => 'encarregado.edit',
        'destroy' => 'encarregado.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('disciplinas', 'SubjectsManagementController', [
      'names' => [
        'index'   => 'disciplinas',
        'edit' => 'disciplina.edit',
        'destroy' => 'disciplina.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('contactos', 'ContactosManagementController', [
      'names' => [
        'index'   => 'contactos',
        'show' => 'contacto.show',
        'edit' => 'contacto.edit',
        'destroy' => 'contacto.destroy',
      ],
      'except' => [
        'deleted',
        'create',
        'store',
      ],
    ]);

    Route::name('estudante.matriculas.readmitir')->get('estudantes/matriculas/readmitir',
                                                       'StudentsManagementController@getReadmitir');
    Route::name('estudante.matriculas.readmitir')->post('estudantes/matriculas/readmitir',
                                                       'StudentsManagementController@postReadmitir');

    Route::resource('estudantes', 'StudentsManagementController', [
      'names' => [
        'index'   => 'estudantes',
        'destroy' => 'estudante.destroy',
      ],
      'except' => [
        'deleted',
      ],
    ]);

    Route::resource('pagamentos', 'PaymentsManagementController', [
      'names' => [
        'index'   => 'pagamentos',
        'destroy' => 'pagamento.destroy',
      ],
    ]);


    Route::get('estudantes/adicionar/notas/create/{id}',[
      'as'=> 'estudante.notas.add.create',
      'uses' => 'AdminMarksManagementController@create'
    ]);

    Route::resource('estudantes/adicionar/notas',
      'AdminMarksManagementController',[
      'names' => [
        'index' => 'estudante.notas.add.index',
        'show'   =>  'estudante.notas.add.show',
        'store'  => 'estudante.notas.add.store',
      ],
      'except' => [
        'create',
        'edit',
      ],
    ]);

    Route::get('estudantes/adicionar/notas/ver/{student}', [
      'as' => 'student.get.marks',
      'uses' => 'AdminMarksManagementController@getMarks'
    ]);

    Route::get('estudantes/adicionar/notas/ver/current/{student}', [
      'as' => 'student.get.current.marks',
      'uses' => 'AdminMarksManagementController@getCurrentMarks'
    ]);

    Route::get('estudantes/adicionar/notas/ver/current/{student}/subject', [
      'as' => 'student.get.current.marks.by.subject',
      'uses' => 'AdminMarksManagementController@getCurrentMarksBySubject'
    ]);

    Route::get('estudantes/adicionar/disciplinas/ver/{student}', [
      'as' => 'student.get.subjects',
      'uses' => 'AdminMarksManagementController@getSubjects'
    ]);

    Route::resource('temas', 'ThemesManagementController', [
      'names' => [
        'index'   => 'temas',
        'show' => 'tema.show',
        'edit' => 'tema.edit',
        'destroy' => 'tema.destroy',
      ],
    ]);

    Route::group(['prefix' => 'admin'], function(){

web/app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
  protected $table = 'estudantes';

  protected $fillable = [
    'primeiro_nome',
    'sobrenome',
    'sexo',
    'nr_de_reg',
    'data_de_nascimento',
    'telefone',
    'endereco',
    'bilhete_de_identidade',
    'profissao',
    'estado_civil',
    'encarregado_id',
    'professor_id'
  ];

  public function user()
  {
    return $this->morphOne('App\Models\User', 'userable');
  }

  public function results()
  {
    return $this->hasMany('App\Models\Result');
  }

  public function encarregado()
  {
    return $this->belongsTo('App\Models\Guardian', 'encarregado_id');
  }

  public function matriculas()
  {
    return $this->hasMany('App\Models\Matricula', 'estudante_id');
  }

  public function disciplinas_cursadas()
  {
    return $this->hasMany('App\Models\StudentSubjectTaken', 'estudante_id');
  }

  public function getFullNomeAttribute()
  {
    return $this->primeiro_nome . " " . $this->sobrenome;
  }

  public function getNomeAttribute()
  {
    return $this->primeiro_nome . " " . $this->sobrenome;
  }
}

web/resources/views/website/pages/noticias/index.blade.php
@extends('layouts.landing')
@section('content')
  <div class="news-area page-content-area">
    <div class="container">
      <div class="row page-title">
        <div class="col-md-6">
          <div>
            <h1>@lang('app.allNews')</h1>
          </div>
        </div>
        <div class="col-md-6">
          <nav aria-label="pagination"></nav>
        </div>
        <div class="col"><hr></div>
      </div>
      <div class="row">
        @foreach($noticias as $key => $noticia)
          <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card ekattor-grid-news">
              <img class="card-img-top img-fluid" alt="" src="{{ $noticia->imagem}}">
              <div class="card-body">
                <h3 class="card-title">
                  <a href="{{ route("noticias.show", $noticia->id)}}">{{ $noticia->titulo}}</a>
                </h3>
                @php
                  $descricao = str_limit($noticia->descricao, 100);
                  $descricao = strip_tags($descricao);
                @endphp
                <p class="card-text">{!! $descricao !!}</p>
                <hr>
                <p class="card-text pull-left">
                  <small class="text-muted">
                    {{$noticia->created_at->format('d M, Y')}}
                  </small>
                </p>
                <a href="{{ route("noticias.show", $noticia->id)}}" class="pull-right btn">
                  @lang("app.readMore")..
                </a>
              </div>
            </div>
          </div>
        @endforeach
      </div>
      <div class="row">
        <div class="col">
          <div class="event-list-pagination">
            <nav aria-label="pagination">
              {!! $noticias->render() !!}
            </nav>
          </div>
        </div>
      </div>

        {{-- <aside class="page-sidebar  col-md-3 col-md-offset-1 col-sm-4 col-sm-offset-1">
          <section class="widget has-divider">
            <h3 class="title">Arcu Aliquet Quam Vel</h3>
            <p>Maecenas nisl urna, condimentum ac justo a, adipiscing hendrerit magna. Fusce pharetra laoreet accumsan. Phasellus elit sapien, consequat vel sapien sit amet, condimentum vulputate odio. Aliquam fringilla justo quis est placerat, eu imperdiet lorem cursus. Curabitur pretium nulla lorem, sed egestas ante vestibulum dignissim.</p>
          </section><!--//widget-->
          <section class="widget has-divider">
            <h3 class="title">@lang("app.upcomingEvents")</h3>
            @foreach($eventos as $key => $evento)
              <article class="events-item row page-row">
                <div class="date-label-wrapper col-md-3 col-sm-4 col-xs-4">
                    <p class="date-label">
                        <span class="month">{{$evento->data->format('M')}}</span>
                        <span class="date-number">{{$evento->data->format('d')}}</span>
                    </p>
                </div><!--//date-label-wrapper-->
                <div class="details col-md-9 col-sm-8 col-xs-8">
                    <h5 class="title">{{$evento->nome}}</h5>
                    <p class="time text-muted">{{$evento->hora_de_comeco}} - {{$evento->hora_de_termino}}
                      <br/>{{$evento->lugar}}
                    </p>
                </div><!--//details-->
              </article>
            @endforeach
          </section><!--//widget-->
        </aside> --}}
    </div>
  </div>
@endsection

web/resources/views/website/pages/noticias/show.blade.php
@extends('layouts.landing')
@section('content')
  <div class="single-news-area page-content-area">
    <div class="container">
      <div class="row">
        {{-- <header class="page-heading clearfix">
          <h1 class="heading-title pull-left">{{$noticia->titulo}}</h1>
          <div class="breadcrumbs pull-right">
            <ul class="breadcrumbs-list">
              <li class="breadcrumbs-label">@lang('app.youAreHere'):</li>
              <li><a href="{{ route('home') }}">@lang('app.home')</a><i class="fa fa-angle-right"></i></li>
              <li><a href="{{ route('noticias.index') }}">@lang('app.news')</a><i class="fa fa-angle-right"></i></li>
              <li class="current">{{$noticia->titulo}}</li>
            </ul>
          </div><!--//breadcrumbs-->
        </header> --}}
        <div class="col-lg-8 col-md-12">
          <div class="single-news-wrapper" id="notice-print">
            <div class="news-header clearfix">
              <div class="left-title pull-left">
                <h1 class="news-title">
                  {{ $noticia->titulo}}
                </h1>
                <span class="news-meta">{{$noticia->created_at->format('d M, Y')}}</span>
              </div>
              <div class="right-btn pull-right">
                <button type="button" class="btn btn-sm btn-outline-dark d-print-none"
                  onclick="printDiv('notice-print')">Print
                </button>
              </div>
            </div>
            <div class="news-image">
              <img src="{{ $noticia->imagem}}" alt="" class="img-fluid">
            </div>
            <div class="page-content">
              {!! $noticia->descricao !!}
            </div>
          </div>
        </div>
        <div class="col-lg-4 col-md-12">
          <div class="sidebar-widgets">
            <div class="widgets recent-news-widget">
              <div class="widget-title">
                <h4>@lang('app.news')</h4>
              </div>
              <div class="widgets-content">
                <ul>
                  @foreach($noticias as $key => $noticia)
                    <li>
                      <h5 class="news-title">
                        <a href="{{ route("noticias.show", $noticia->id)}}">
                          {{ $noticia->titulo}}
                        </a>
                      </h5>
                      <span class="meta">{{$noticia->created_at->format('d M, Y')}}</span>
                    </li>
                  @endforeach
                </ul>
              </div>
            </div>
            <div class="widgets recent-events-widget">
              <div class="widget-title">
                <h4>@lang('app.events')</h4>
              </div>
              <div class="widgets-content">
                <ul>
                  @foreach($eventos as $key => $event)
                    <li>
                      <h5 class="news-title">
                        <a>
                          {{ $event->nome}}
                        </a>
                      </h5>
                      <span class="meta">{{$event->created_at->format('d M, Y')}}</span>
                    </li>
                  @endforeach
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection